import React from "react";
import { Form } from "react-bootstrap";

function DutyLocationSelector() {
  const militaryLocations = [
    "Andrews Air Force Base, MD",
    "Barksdale Air Force Base, LA",
    "Beale Air Force Base, CA",
    "Campbell Army Airfield, KY",
    "Carlisle Barracks, PA",
    "Davis-Monthan Air Force Base, AZ",
    "Dover Air Force Base, DE",
    "Dyess Air Force Base, TX",
    "Edwards Air Force Base, CA",
    "Eglin Air Force Base, FL",
    "Ellsworth Air Force Base, SD",
    "F.E. Warren Air Force Base, WY",
    "Fairchild Air Force Base, WA",
    "Fort Belvoir, VA",
    "Fort Benning, GA",
    "Fort Bliss, TX",
    "Fort Bragg, NC",
    "Fort Campbell, KY",
    "Fort Carson, CO",
    "Fort Detrick, MD",
    "Fort Drum, NY",
    "Fort Eustis, VA",
    "Fort Gordon, GA",
    "Fort Hood, TX",
    "Fort Huachuca, AZ",
    "Fort Irwin, CA",
    "Fort Jackson, SC",
    "Fort Knox, KY",
    "Fort Leavenworth, KS",
    "Fort Lee, VA",
    "Fort Leonard Wood, MO",
    "Fort McCoy, WI",
    "Fort Meade, MD",
    "Fort Polk, LA",
    "Fort Riley, KS",
    "Fort Rucker, AL",
    "Fort Sam Houston, TX",
    "Fort Sill, OK",
    "Fort Stewart, GA",
    "Fort Wainwright, AK",
    "Goodfellow Air Force Base, TX",
    "Grand Forks Air Force Base, ND",
    "Hanscom Air Force Base, MA",
    "Hill Air Force Base, UT",
    "Holloman Air Force Base, NM",
    "Hunter Army Airfield, GA",
    "Joint Base Andrews, MD",
    "Joint Base Anacostia-Bolling, DC",
    "Joint Base Charleston, SC",
    "Joint Base Elmendorf-Richardson, AK",
    "Joint Base Langley-Eustis, VA",
    "Joint Base Lewis-McChord, WA",
    "Joint Base McGuire-Dix-Lakehurst, NJ",
    "Joint Base Myer-Henderson Hall, VA",
    "Joint Base Pearl Harbor-Hickam, HI",
    "Joint Base San Antonio, TX",
    "Joint Expeditionary Base Little Creek-Fort Story, VA",
    "Joint Region Marianas, Guam",
    "Keesler Air Force Base, MS",
    "Kirtland Air Force Base, NM",
    "Lackland Air Force Base, TX",
    "Langley Air Force Base, VA",
    "Laughlin Air Force Base, TX",
    "Little Rock Air Force Base, AR",
    "Los Angeles Air Force Base, CA",
    "Luke Air Force Base, AZ",
    "MacDill Air Force Base, FL",
    "Malmstrom Air Force Base, MT",
    "Marine Corps Air Station Cherry Point, NC",
    "Marine Corps Air Station Miramar, CA",
    "Marine Corps Air Station New River, NC",
    "Marine Corps Air Station Yuma, AZ",
    "Marine Corps Base Camp Butler, Japan",
    "Marine Corps Base Camp Lejeune, NC",
    "Marine Corps Base Camp Pendleton, CA",
    "Marine Corps Base Quantico, VA",
    "Marine Corps Logistics Base Albany, GA",
    "Marine Corps Logistics Base Barstow, CA",
    "Marine Corps Mountain Warfare Training Center, CA",
    "Marine Corps Recruit Depot Parris Island, SC",
    "Marine Corps Recruit Depot San Diego, CA",
    "Maxwell Air Force Base, AL",
    "McChord Field (Joint Base Lewis-McChord), WA",
    "Minot Air Force Base, ND",
    "Moody Air Force Base, GA",
    "Mountain Home Air Force Base, ID",
    "Naval Air Facility El Centro, CA",
    "Naval Air Station Corpus Christi, TX",
    "Naval Air Station Fallon, NV",
    "Naval Air Station Jacksonville, FL",
    "Naval Air Station Joint Reserve Base Fort Worth, TX",
    "Naval Air Station Joint Reserve Base New Orleans, LA",
    "Naval Air Station Key West, FL",
    "Naval Air Station Kingsville, TX",
    "Naval Air Station Lemoore, CA",
    "Naval Air Station Meridian, MS",
    "Naval Air Station North Island, CA",
    "Naval Air Station Oceana, VA",
    "Naval Air Station Patuxent River, MD",
    "Naval Air Station Pensacola, FL",
    "Naval Air Station Whidbey Island, WA",
    "Naval Base Coronado, CA",
    "Naval Base Guam",
    "Naval Base Kitsap, WA",
    "Naval Base Point Loma, CA",
    "Naval Base San Diego, CA",
    "Naval Base Ventura County, CA",
    "Naval Construction Battalion Center Gulfport, MS",
    "Naval Postgraduate School, CA",
    "Naval Station Everett, WA",
    "Naval Station Great Lakes, IL",
    "Naval Station Mayport, FL",
    "Naval Station Newport, RI",
    "Naval Station Norfolk, VA",
    "Naval Station Rota, Spain",
    "Naval Submarine Base Kings Bay, GA",
    "Naval Submarine Base New London, CT",
    "Naval Support Activity Bethesda, MD",
    "Naval Support Activity Hampton Roads, VA",
    "Naval Support Activity Mechanicsburg, PA",
    "Naval Support Activity Mid-South, TN",
    "Naval Support Activity Monterey, CA",
    "Naval Support Activity Naples, Italy",
    "Naval Support Activity Orlando, FL",
    "Naval Support Activity Panama City, FL",
    "Naval Support Activity Philadelphia, PA",
    "Naval Support Activity Saratoga Springs, NY",
    "Naval Support Activity Washington, DC",
    "Naval Weapons Station Charleston, SC",
    "Naval Weapons Station Earle, NJ",
    "Naval Weapons Station Yorktown, VA",
    "Nellis Air Force Base, NV",
    "Offutt Air Force Base, NE",
    "Patrick Space Force Base, FL",
    "Pentagon, VA",
    "Peterson Space Force Base, CO",
    "Picatinny Arsenal, NJ",
    "Pine Bluff Arsenal, AR",
    "Pueblo Chemical Depot, CO",
    "Redstone Arsenal, AL",
    "Robins Air Force Base, GA",
    "Rock Island Arsenal, IL",
    "Schriever Space Force Base, CO",
    "Scott Air Force Base, IL",
    "Seymour Johnson Air Force Base, NC",
    "Shaw Air Force Base, SC",
    "Sheppard Air Force Base, TX",
    "Travis Air Force Base, CA",
    "Tyndall Air Force Base, FL",
    "United States Air Force Academy, CO",
    "United States Military Academy, NY",
    "United States Naval Academy, MD",
    "Vandenberg Space Force Base, CA",
    "Walter Reed National Military Medical Center, MD",
    "Westover Air Reserve Base, MA",
    "Whiteman Air Force Base, MO",
    "Wright-Patterson Air Force Base, OH",
  ];
  return (
    <Form.Group controlId="DutyLocation">
      <Form.Label>Duty Location</Form.Label>
      <Form.Control
        list="militaryLocations"
        placeholder="Type or select a location"
      />
      <datalist id="militaryLocations">
        {militaryLocations.map((location, index) => (
          <option key={index} value={location} />
        ))}
      </datalist>
    </Form.Group>
  );
}

export default DutyLocationSelector;
