import React, { useState } from "react";
import { Form, Row, Col } from "react-bootstrap";

function CountrySelector({ country, setCountry }) {
  const countries = [
    { name: "AFGHANISTAN", abbreviation: "AF" },
    { name: "ALBANIA", abbreviation: "AL" },
    { name: "ALGERIA", abbreviation: "DZ" },
    { name: "ANDORRA", abbreviation: "AD" },
    { name: "ANGOLA", abbreviation: "AO" },
    { name: "ARGENTINA", abbreviation: "AR" },
    { name: "ARMENIA", abbreviation: "AM" },
    { name: "AUSTRALIA", abbreviation: "AU" },
    { name: "AUSTRIA", abbreviation: "AT" },
    { name: "AZERBAIJAN", abbreviation: "AZ" },
    { name: "BAHAMAS", abbreviation: "BS" },
    { name: "BAHRAIN", abbreviation: "BH" },
    { name: "BANGLADESH", abbreviation: "BD" },
    { name: "BARBADOS", abbreviation: "BB" },
    { name: "BELARUS", abbreviation: "BY" },
    { name: "BELGIUM", abbreviation: "BE" },
    { name: "BELIZE", abbreviation: "BZ" },
    { name: "BENIN", abbreviation: "BJ" },
    { name: "BHUTAN", abbreviation: "BT" },
    { name: "BOLIVIA", abbreviation: "BO" },
    { name: "BOSNIA AND HERZEGOVINA", abbreviation: "BA" },
    { name: "BOTSWANA", abbreviation: "BW" },
    { name: "BRAZIL", abbreviation: "BR" },
    { name: "BRUNEI DARUSSALAM", abbreviation: "BN" },
    { name: "BULGARIA", abbreviation: "BG" },
    { name: "BURKINA FASO", abbreviation: "BF" },
    { name: "BURUNDI", abbreviation: "BI" },
    { name: "CABO VERDE", abbreviation: "CV" },
    { name: "CAMBODIA", abbreviation: "KH" },
    { name: "CAMEROON", abbreviation: "CM" },
    { name: "CANADA", abbreviation: "CA" },
    { name: "CENTRAL AFRICAN REPUBLIC", abbreviation: "CF" },
    { name: "CHAD", abbreviation: "TD" },
    { name: "CHILE", abbreviation: "CL" },
    { name: "CHINA", abbreviation: "CN" },
    { name: "COLOMBIA", abbreviation: "CO" },
    { name: "COMOROS", abbreviation: "KM" },
    { name: "CONGO", abbreviation: "CG" },
    { name: "COSTA RICA", abbreviation: "CR" },
    { name: "CROATIA", abbreviation: "HR" },
    { name: "CUBA", abbreviation: "CU" },
    { name: "CYPRUS", abbreviation: "CY" },
    { name: "CZECH REPUBLIC", abbreviation: "CZ" },
    { name: "DENMARK", abbreviation: "DK" },
    { name: "DJIBOUTI", abbreviation: "DJ" },
    { name: "DOMINICA", abbreviation: "DM" },
    { name: "DOMINICAN REPUBLIC", abbreviation: "DO" },
    { name: "ECUADOR", abbreviation: "EC" },
    { name: "EGYPT", abbreviation: "EG" },
    { name: "EL SALVADOR", abbreviation: "SV" },
    { name: "EQUATORIAL GUINEA", abbreviation: "GQ" },
    { name: "ERITREA", abbreviation: "ER" },
    { name: "ESTONIA", abbreviation: "EE" },
    { name: "ESWATINI", abbreviation: "SZ" },
    { name: "ETHIOPIA", abbreviation: "ET" },
    { name: "FIJI", abbreviation: "FJ" },
    { name: "FINLAND", abbreviation: "FI" },
    { name: "FRANCE", abbreviation: "FR" },
    { name: "GABON", abbreviation: "GA" },
    { name: "GAMBIA", abbreviation: "GM" },
    { name: "GEORGIA", abbreviation: "GE" },
    { name: "GERMANY", abbreviation: "DE" },
    { name: "GHANA", abbreviation: "GH" },
    { name: "GREECE", abbreviation: "GR" },
    { name: "GRENADA", abbreviation: "GD" },
    { name: "GUATEMALA", abbreviation: "GT" },
    { name: "GUINEA", abbreviation: "GN" },
    { name: "GUINEA-BISSAU", abbreviation: "GW" },
    { name: "GUYANA", abbreviation: "GY" },
    { name: "HAITI", abbreviation: "HT" },
    { name: "HONDURAS", abbreviation: "HN" },
    { name: "HUNGARY", abbreviation: "HU" },
    { name: "ICELAND", abbreviation: "IS" },
    { name: "INDIA", abbreviation: "IN" },
    { name: "INDONESIA", abbreviation: "ID" },
    { name: "IRAN", abbreviation: "IR" },
    { name: "IRAQ", abbreviation: "IQ" },
    { name: "IRELAND", abbreviation: "IE" },
    { name: "ISRAEL", abbreviation: "IL" },
    { name: "ITALY", abbreviation: "IT" },
    { name: "JAMAICA", abbreviation: "JM" },
    { name: "JAPAN", abbreviation: "JP" },
    { name: "JORDAN", abbreviation: "JO" },
    { name: "KAZAKHSTAN", abbreviation: "KZ" },
    { name: "KENYA", abbreviation: "KE" },
    { name: "KIRIBATI", abbreviation: "KI" },
    { name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", abbreviation: "KP" },
    { name: "KOREA, REPUBLIC OF", abbreviation: "KR" },
    { name: "KUWAIT", abbreviation: "KW" },
    { name: "KYRGYZSTAN", abbreviation: "KG" },
    { name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", abbreviation: "LA" },
    { name: "LATVIA", abbreviation: "LV" },
    { name: "LEBANON", abbreviation: "LB" },
    { name: "LESOTHO", abbreviation: "LS" },
    { name: "LIBERIA", abbreviation: "LR" },
    { name: "LIBYA", abbreviation: "LY" },
    { name: "LIECHTENSTEIN", abbreviation: "LI" },
    { name: "LITHUANIA", abbreviation: "LT" },
    { name: "LUXEMBOURG", abbreviation: "LU" },
    { name: "MADAGASCAR", abbreviation: "MG" },
    { name: "MALAWI", abbreviation: "MW" },
    { name: "MALAYSIA", abbreviation: "MY" },
    { name: "MALDIVES", abbreviation: "MV" },
    { name: "MALI", abbreviation: "ML" },
    { name: "MALTA", abbreviation: "MT" },
    { name: "MARSHALL ISLANDS", abbreviation: "MH" },
    { name: "MAURITANIA", abbreviation: "MR" },
    { name: "MAURITIUS", abbreviation: "MU" },
    { name: "MEXICO", abbreviation: "MX" },
    { name: "MICRONESIA (FEDERATED STATES OF)", abbreviation: "FM" },
    { name: "MOLDOVA, REPUBLIC OF", abbreviation: "MD" },
    { name: "MONACO", abbreviation: "MC" },
    { name: "MONGOLIA", abbreviation: "MN" },
    { name: "MONTENEGRO", abbreviation: "ME" },
    { name: "MOROCCO", abbreviation: "MA" },
    { name: "MOZAMBIQUE", abbreviation: "MZ" },
    { name: "MYANMAR", abbreviation: "MM" },
    { name: "NAMIBIA", abbreviation: "NA" },
    { name: "NAURU", abbreviation: "NR" },
    { name: "NEPAL", abbreviation: "NP" },
    { name: "NETHERLANDS", abbreviation: "NL" },
    { name: "NEW ZEALAND", abbreviation: "NZ" },
    { name: "NICARAGUA", abbreviation: "NI" },
    { name: "NIGER", abbreviation: "NE" },
    { name: "NIGERIA", abbreviation: "NG" },
    { name: "NORTH MACEDONIA", abbreviation: "MK" },
    { name: "NORWAY", abbreviation: "NO" },
    { name: "OMAN", abbreviation: "OM" },
    { name: "PAKISTAN", abbreviation: "PK" },
    { name: "PALAU", abbreviation: "PW" },
    { name: "PALESTINE, STATE OF", abbreviation: "PS" },
    { name: "PANAMA", abbreviation: "PA" },
    { name: "PAPUA NEW GUINEA", abbreviation: "PG" },
    { name: "PARAGUAY", abbreviation: "PY" },
    { name: "PERU", abbreviation: "PE" },
    { name: "PHILIPPINES", abbreviation: "PH" },
    { name: "POLAND", abbreviation: "PL" },
    { name: "PORTUGAL", abbreviation: "PT" },
    { name: "QATAR", abbreviation: "QA" },
    { name: "ROMANIA", abbreviation: "RO" },
    { name: "RUSSIAN FEDERATION", abbreviation: "RU" },
    { name: "RWANDA", abbreviation: "RW" },
    { name: "SAINT KITTS AND NEVIS", abbreviation: "KN" },
    { name: "SAINT LUCIA", abbreviation: "LC" },
    { name: "SAINT VINCENT AND THE GRENADINES", abbreviation: "VC" },
    { name: "SAMOA", abbreviation: "WS" },
    { name: "SAN MARINO", abbreviation: "SM" },
    { name: "SAO TOME AND PRINCIPE", abbreviation: "ST" },
    { name: "SAUDI ARABIA", abbreviation: "SA" },
    { name: "SENEGAL", abbreviation: "SN" },
    { name: "SERBIA", abbreviation: "RS" },
    { name: "SEYCHELLES", abbreviation: "SC" },
    { name: "SIERRA LEONE", abbreviation: "SL" },
    { name: "SINGAPORE", abbreviation: "SG" },
    { name: "SLOVAKIA", abbreviation: "SK" },
    { name: "SLOVENIA", abbreviation: "SI" },
    { name: "SOLOMON ISLANDS", abbreviation: "SB" },
    { name: "SOMALIA", abbreviation: "SO" },
    { name: "SOUTH AFRICA", abbreviation: "ZA" },
    { name: "SOUTH SUDAN", abbreviation: "SS" },
    { name: "SPAIN", abbreviation: "ES" },
    { name: "SRI LANKA", abbreviation: "LK" },
    { name: "SUDAN", abbreviation: "SD" },
    { name: "SURINAME", abbreviation: "SR" },
    { name: "SWEDEN", abbreviation: "SE" },
    { name: "SWITZERLAND", abbreviation: "CH" },
    { name: "SYRIAN ARAB REPUBLIC", abbreviation: "SY" },
    { name: "TAIWAN", abbreviation: "TW" },
    { name: "TAJIKISTAN", abbreviation: "TJ" },
    { name: "TANZANIA, UNITED REPUBLIC OF", abbreviation: "TZ" },
    { name: "THAILAND", abbreviation: "TH" },
    { name: "TIMOR-LESTE", abbreviation: "TL" },
    { name: "TOGO", abbreviation: "TG" },
    { name: "TONGA", abbreviation: "TO" },
    { name: "TRINIDAD AND TOBAGO", abbreviation: "TT" },
    { name: "TUNISIA", abbreviation: "TN" },
    { name: "TURKEY", abbreviation: "TR" },
    { name: "TURKMENISTAN", abbreviation: "TM" },
    { name: "TUVALU", abbreviation: "TV" },
    { name: "UGANDA", abbreviation: "UG" },
    { name: "UKRAINE", abbreviation: "UA" },
    { name: "UNITED ARAB EMIRATES", abbreviation: "AE" },
    { name: "UNITED KINGDOM", abbreviation: "GB" },
    { name: "UNITED STATES", abbreviation: "US" },
    { name: "URUGUAY", abbreviation: "UY" },
    { name: "UZBEKISTAN", abbreviation: "UZ" },
    { name: "VANUATU", abbreviation: "VU" },
    { name: "VENEZUELA", abbreviation: "VE" },
    { name: "VIET NAM", abbreviation: "VN" },
    { name: "YEMEN", abbreviation: "YE" },
    { name: "ZAMBIA", abbreviation: "ZM" },
    { name: "ZIMBABWE", abbreviation: "ZW" },
  ];

  return (
    <Form.Group>
      <Form.Label>Country Selector</Form.Label>
      <Form.Control
        value={country}
        autoComplete="country"
        list="countriesList"
        placeholder="Type or select your country"
        onChange={(e) => setCountry(e.target.value)}
      />
      <datalist id="countriesList">
        {countries.map((country) => (
          <option key={country.abbreviation} value={country.name}>
            {country.name}
          </option>
        ))}
      </datalist>
    </Form.Group>
  );
}

export default CountrySelector;
